### ISSUE TITLE
Display tiny with scrollbars

### ISSUE THREAD

**Issue by PamilerinId** [ashinzekene/angular4-paystack#10]
hi
used the tag in my payment component, the only tag on the page.
but the form loads in a box at the middle top of the page with a scrollbar...

Am i doing something wrong?
PS. Css styles do not affect the tag

**Comment by ashinzekene** [comment]
What tag?

Which component are you using?

Have you inspected the DOM to check what's overflowing?

**Comment by PamilerinId** [comment]
Thank you for your quick response.

> What tag?
> 
> Which component are you using?

this `<angular4-paystack-embed>` tag/component

> Have you inspected the DOM to check what's overflowing?

Yes screenshot below:

 ![screenshot 221 _li](https://user-images.githubusercontent.com/18377080/50845032-40702d80-136c-11e9-96c5-99d753448cdb.jpg)

**Comment by PamilerinId** [comment]
Already had that in place and just for kicks, made the containing component 100% too, no changes
in my case, my payment component exists as a child of my dashboard component...

I suspect its the iframe its loading in?

**Comment by ashinzekene** [comment]
The issue is neither from paystack or the plugin

Please check your code well. You can read the [paystack documentation](https://developers.paystack.co/docs/paystack-embded) for more info about this

**Comment by PamilerinId** [comment]
reused the component in top-level components, same behaviour. Although , now discovered that it resizes to full width when any content is placed above it.

**Comment by ashinzekene** [comment]
Sorry for misunderstanding you.

@steveamaza can you please take a look at this

**Comment by steveamaza** [comment]
@PamilerinId @ashinzekene is the inline embed option? Or is this the pop? The inline method is currently deprecated and we advise devs to build a checkout form instead if they want it embed. We have a library for that https://developers.paystack.co/v2.0/docs/paystack-custom

**Comment by ashinzekene** [comment]
It's the embed. 

Cool, about the new library

**Comment by PamilerinId** [comment]
Thank You @Both for the timely support.
@ashinzekene does this mean this plugin is sort of outdated now.
@steveamaza the library might just fit snugly in my angular flow, will try it out.

Thanks again.
