### ISSUE TITLE
reference is not being updated on the $event on payment done

### ISSUE THREAD

**Issue by Chigozie391** [ashinzekene/angular4-paystack#11]
<button
      angular4-paystack
      [key]="'pk_test_5c4f5d145c5e613e2be0756a2d7ff1a9faf51527'"
      [email]="currentUser?.email"
      [amount]="totalPrice * 100"
      [ref]="reference"
      (close)="paymentCancelled()"
      (callback)="paymentDone($event)"
      id="paystackbtn"
      [hidden]="true"
    ></button>

ngOnInit() {
	  this.reference = Math.floor(Math.random() * 1000000000 + 1);
}

Using a success test card and  making an initial payment, i get the passed reference from the event like $event.reference. Then i navigate to another componenet  this.router.navigate(['/']);

Here is the issue,
When i navigate to my checkout page, ngOnint runs again which updates the reference, but on payment done $event.reference shows the old reference even though its now changed to something else. Yet payment is successful, but it doesnt show the duplicate payment on paystack transaction dashboard.

See if the $event reference is being updated

**Comment by ashinzekene** [comment]
Paystack shows the payment reference on the modal after successful payment. Is this the same as the one you got from the $event object?

**Comment by Chigozie391** [comment]
In a nut shell, I can't update the value of ([ref]=reference) reference after an initial payment has been made... Untill the page is refreshed

**Comment by Chigozie391** [comment]
We can do a zoom or Skype call so you can fully understand

**Comment by ashinzekene** [comment]
I think I now understand you


You can create a PR if you feel

**Comment by Chigozie391** [comment]
Since we are using a test card, in the first payment, we choose a test card let's say success, the payment succeeds
On the second payment without refreshing... Paystack doesn't ask for card details again... Its just completes the payment immediately...thats the problem.

 If there is way to clear cache or something it would fix it. I can't do it my self now.

**Comment by ashinzekene** [comment]
The payment options are computed when the component initiated that's why the can't be changed presently. I'd resolve that

**Comment by Chigozie391** [comment]
Thanks alot, this will really help me out

**Comment by Chigozie391** [comment]
hello, any update on this

**Comment by ashinzekene** [comment]
Adding and OnChanges method to the component would solve this.

You can create a PR, or I'd do it when I'm a bit free

**Comment by Chigozie391** [comment]
I need permission to make a pr

**Comment by ashinzekene** [comment]
You're fine now. You can also use

[PAYSTACK SIMPLE](https://www.npmjs.com/package/paystack-simple)
