### ISSUE TITLE
Not closing page after Paystack Authorization

### ISSUE THREAD

**Issue by Hatimjamali** [ashinzekene/angular4-paystack#14]
we have ionic3 app , when testing for iOS platform after entering Hard token, getting "Paystack Authorization" page and after few second getting another page where it is written "Please close this web page to continue", there is no button to close and not closing automatically, due to this unable to generate order, but payment deducted from credit card.

Hello PayStack Support Team,

We have successfully integrated paystack angular 4 Paystack Inline (Directive) in ionic 3 based application  and its working fine on android.

Currenlty we are using these lines of code to intiate and proceed checkout with paystack
<button
    angular4-paystack
    [key]="'pk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxx'"
    [email]="'mailexample@mail.com'"
    [amount]="5000000"
    [ref]="'2637458697'"
    [class]="'btn btn-primary'"
    (close)="paymentCancel()"
    (callback)="paymentDone($event)">Pay with Paystack</button>

The problem comes when we have generated build for ios platform. I have added this line into config.xml to open internal iframe by the help of 
this configuration.

inside <platform name="ios"> section i have added this line to enable iframe working for ios 

<allow-navigation href="*" />

by this payment flow is start and completed. but in the last screen we are not getting the close button to close internal iframe popup screen
please help us and let us know how to achieve this 

Note -: we have tested paystack payment flow on iphone 6s with ios version 12.2.

[iOS paystack not closing.zip](https://github.com/ashinzekene/angular4-paystack/files/3081189/iOS.paystack.not.closing.zip)

**Comment by ashinzekene** [comment]
Please is it possible to create a sample sandbox?

**Comment by Hatimjamali** [comment]
i don't know how to create sample sandbox.

i can share code, if you need.

**Comment by ashinzekene** [comment]
Sorry for not being explicit enough, I mean you should try reproducing the issue on [Codesandbox](https://codesandbox.io/) or [Stackblitz](https://stackblitz.com/). Sharing the code is fine

**Comment by Hatimjamali** [comment]
below link is for ionic3 code.
http://www.mediafire.com/file/j74jbqtffbfqf3a/M3iOS.rar/file

**Comment by Hatimjamali** [comment]
any update??

**Comment by ashinzekene** [comment]
Please is it possible to host a sample of your code in any of the platforms listed here ?
https://github.com/ashinzekene/angular4-paystack/issues/14#issuecomment-486260041

**Comment by Hatimjamali** [comment]
already given link on above comment, but anyway again giving below link.
http://www.mediafire.com/file/j74jbqtffbfqf3a/M3iOS.rar/file

this is ionic hybrid code applicable for both platform including iOS

**Comment by iameronmosele** [comment]
was this problem solved cause i kind of have the same issue

**Comment by ashinzekene** [comment]
What version of the library are you using?

**Comment by ashinzekene** [comment]
Please checkout https://paystack.com/docs/guides/using_the_paystack_checkout_in_a_mobile_webview

**Comment by kingalingaling** [comment]
Still experiencing when users try to pay on Instagram browser
