### ISSUE TITLE
New Angular PayStack 3.0

### ISSUE THREAD

**Issue by skemuel007** [ashinzekene/angular4-paystack#22]
I implemented the new paystack 3.0 in my project. Using the test key, but your callback function does not return any reference.
It may interest you to know that test payments are successful, email sent but the callback function returns nothing.
    <button
      angular4-paystack
      [email]="applicant.email"
      [amount]="5000000"
      [ref]="reference"
      [key]="'pk_test_************************************"
      [class]="'btn btn-primary'"
      (paymentInit)="paymentInit($event)"
      (close)="paymentCancel()"
      (callback)="paymentDone($event)"
      class="btn btn-primary">
      Pay with PayStack
    </button>
paymentDone(ref: any) {
    console.log(ref);
}
Note: I starred the test key above on purpose
Please I need help

**Comment by ashinzekene** [comment]
Please verify you used it the right way

`https://codesandbox.io/s/gallant-kirch-5qgz2`

**Comment by ashinzekene** [comment]
If you still have issues you can comment under this
