### ISSUE TITLE
Modal does not open again after being closed  unless i reload the page

### ISSUE THREAD

**Issue by sleez007** [ashinzekene/angular4-paystack#23]
i noticed closing the modal does not trigger callback method specified in close event listener. Then also after closing the modal, i cannot reopen the modal again. I am using Angular 8 for my project

**Comment by sleez007** [comment]
downgrading to a lower version of the library actually fixed this issue. Thanks bro

**Comment by ashinzekene** [comment]
Oh, what version of angular are you using?

**Comment by sleez007** [comment]
Angular CLI: 8.3.23
Node: 10.15.3
Angular: 8.2.14

**Comment by lukman008** [comment]
@sleez007 Which version of the library did you downgrade to?

**Comment by lukman008** [comment]
Got it, thanks @sleez007
