### ISSUE TITLE
Possibility to show saved cards

### ISSUE THREAD

**Issue by balavishnu** [ashinzekene/angular4-paystack#26]
Hi, is it possible to save the card entered by the customer and show it again the next time he comes in?

**Comment by ashinzekene** [comment]
You 'd have to tokenize the cards
https://developers.paystack.co/v2.0/docs/recurring-debits

**Comment by balavishnu** [comment]
@ashinzekene ok, I understand that I will need to take the "ref.data.authorization" from paymentDone() save it in the backend.

After that should I build my own UI to show the saved cards? Cant we pass the authorisation into the library and the library render the cards? Do we have any such option?

**Comment by ashinzekene** [comment]
No, the library is just for showing the payment modals.
You would need to design your own UI for that
