### ISSUE TITLE
Set Transaction Channels

### ISSUE THREAD

**Issue by Austyns** [ashinzekene/angular4-paystack#3]
This is not an issue, more like an enhancement.  
Please can you add the channels option where one can dynamically set channels as bank or card. 

Or can you add some some directions as to contributing to your library. 

Thanks in advance

**Comment by ashinzekene** [comment]
https://medium.com/consonance/building-an-angular-library-with-the-angular-cli-version-6-384ee85933ad

That's a link to a post I wrote about creating an angular library. 

Are you going to make a PR or should I?
