### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by franklobsty25** [ashinzekene/angular4-paystack#35]
Attached is the error I get when installing angular4-paystack in my project

![Screenshot 2021-05-24 at 9 35 27 AM](https://user-images.githubusercontent.com/76218199/119330281-93b15500-bc75-11eb-9292-f0818eeb51a9.jpg)

**Comment by ashinzekene** [comment]
Seems you're using angular 11. The library hasn't been updated to v11 yet. You can use `--foce` to skip this error.

I'd work on making an update soon. You can also create a PR of you wish. Thanks

**Comment by franklobsty25** [comment]
Please will it work if I use --force.
Also PR stand for

**Comment by ashinzekene** [comment]
Yes. It should. 

Pull request. 
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by franklobsty25** [comment]
Thanks very much is working now but when the inline iframe opens. An error message show saying currency not support in my country as merchants .
Please way forward for it to work for country Ghana.

Thank you

**Comment by franklobsty25** [comment]
<img width="384" alt="Screenshot 2021-05-24 at 4 51 11 PM" src="https://user-images.githubusercontent.com/76218199/119380562-6c2bae00-bcb0-11eb-8885-eb8b355b0ce0.png">

The screenshot of the error message

**Comment by ashinzekene** [comment]
The currency you used isn't supported by paystack. You can check their developer documentation for supported currencies
