### ISSUE TITLE
Empty Email option

### ISSUE THREAD

**Issue by kbbansi** [ashinzekene/angular4-paystack#36]
I'm setting my email option using data stored in a session however I keep getting this error:
'ANGULAR-PAYSTACK: Paystack email cannot be empty'
I've blotted out the email address, but it's proof that the email is being read from session storage
![some email error](https://user-images.githubusercontent.com/20690607/119653288-af079600-be16-11eb-914d-cbbd4aaff485.PNG)

**Comment by ashinzekene** [comment]
How are you passing the email to the component/directive?

**Comment by ashinzekene** [comment]
Closing this, you can reopen if you're still facing the issue
