### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by shivamssh** [ashinzekene/angular4-paystack#37]
Not bale to run application 
Version of 
![image](https://user-images.githubusercontent.com/11404047/123504501-62aeb080-d677-11eb-8242-ac5285ad53f9.png)

![image](https://user-images.githubusercontent.com/11404047/123504445-fe8bec80-d676-11eb-8d9e-57065b906da7.png)
![image](https://user-images.githubusercontent.com/11404047/123504456-119ebc80-d677-11eb-8192-6e3fdb059959.png)
![image](https://user-images.githubusercontent.com/11404047/123504475-3004b800-d677-11eb-9e50-193a169cb125.png)
Please let me know if any solution. Thanks

**Comment by ashinzekene** [comment]
You seem to be using an old version of angular. You need to either update or install an older version of this package. You can try angular4-paystack@1.2.0 or check versions a little after that here
https://www.npmjs.com/package/angular4-paystack

**Comment by shivamssh** [comment]
This time I have updated but still -
![image](https://user-images.githubusercontent.com/11404047/123524550-b1e0f980-d6e8-11eb-9c84-0c7396aee5fb.png)
angular4-paystack@3.0.0

**Comment by ashinzekene** [comment]
What version did you install?

**Comment by shivamssh** [comment]
> What version did you install?

3.0.0, Irrespective of that I am getiing any random issue, I get errors when I install an older version (setup issue) and if I install new then get Object (...) is not a function.

**Comment by ashinzekene** [comment]
Version 3.0 is not compatible with Angular 5. Try `npm i angular4-paystack@1.2.1`
