### ISSUE TITLE
Unable to upgrade to angular 12 from 11

### ISSUE THREAD

**Issue by sleekcoda** [ashinzekene/angular4-paystack#40]
I keep getting this error in the console due to some required dependency in your package

Package "angular4-paystack" has an incompatible peer dependency to "@angular/common" (requires "^8.0.3" (extended), would install "12.2.2").
                  Package "angular4-paystack" has an incompatible peer dependency to "@angular/core" (requires "^8.0.3" (extended), would install "12.2.2").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.

**Comment by ashinzekene** [comment]
Hi @sleekcoda, it's a warning, not an error and should not cause any issues

A peer dependency is the recommended dependency for a package. I think it has been tested to work with angular v12

I could create a PR to make angular versions 8-12 compatible peer dependencies

**Comment by ashinzekene** [comment]
Can you try updating to v3.0.2 and testing

**Comment by sleekcoda** [comment]
> Can you try updating to v3.0.2 and testing

I didn't need to update to this version
I forced the update and it worked after clearing other errors
Thank you!
