### ISSUE TITLE
Inline Embed

### ISSUE THREAD

**Issue by kolawoletech** [ashinzekene/angular4-paystack#47]
Is there a way to change the styling o f the inline embed? I am assuming it is not yet possible, if it is, can you please guide me. I want to keep a rather dark theme

![localhost_8100_home(iPhone X) (1)](https://user-images.githubusercontent.com/4382405/131476905-9359e24e-bd66-465e-98f1-528f7fa2be54.png)

**Comment by ashinzekene** [comment]
@kolawoletech . First the inline embed is deprecated.
Second, I don't think there's is a theming option for popups, you can find out more here
https://paystack.com/docs/payments/accept-payments
