### ISSUE TITLE
callback function not working

### ISSUE THREAD

**Issue by ajanieniolasolomon** [ashinzekene/angular4-paystack#6]
The angular4paystack callback function is not working.pls help me check it out

**Comment by ashinzekene** [comment]
Working now?

**Comment by ajanieniolasolomon** [comment]
Thanks am I too uninstall and install

**Comment by ashinzekene** [comment]
What version of Angular and angular-paystack are you using?

**Comment by ajanieniolasolomon** [comment]
2.2.0

**Comment by ashinzekene** [comment]
Angular?

**Comment by ajanieniolasolomon** [comment]
Angular 7

**Comment by ashinzekene** [comment]
It should work can you paste what you did

**Comment by ajanieniolasolomon** [comment]
import { Component, OnInit, Output } from '@angular/core';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';
import { switchMap } from 'rxjs/operators';
import { PaymentService } from '../../share/payment.service';
import { EventEmitter } from 'events';

@Component({
selector: 'app-pay',
templateUrl: './pay.component.html',
styleUrls: ['./pay.component.css']
})
export class PayComponent implements OnInit {

show= false;
email;
ref;
number;
constructor(
private route: ActivatedRoute,
private router: Router,
private service: PaymentService
) {}

ngOnInit() {

this.hero$ = this.route.paramMap.pipe(
switchMap((params: ParamMap) =>
this.service.makepayment2(params.get('id')))

).subscribe((res:any) => {
this.show = true;
const {email, _id, mobile} = res.fulfillmentText;
this.email = email;
this.ref = _id;
this.number = mobile;

}, err => console.log(err));

}
paymentDone(event) {
console.log('done');
console.log(event);
await this.service.update(this.ref, this.number).subscribe(res => {
console.log("res");
});
}
paymentCancel() {
console.log("close");
}
}
<angular4-paystack-embed *ngIf="show" key=
"pk_test_33c2437bd12c2e1c5358c7701791c02" email="{{email}}" amount="5000000"
ref="{{ref}}" class="'btn btn-primary'" (close)="paymentCancel($event)" (
callback)="paymentDone($event)">
<span class="spinner spinner-inline">
Loading...
</span>
<span>
Loading.</span>
</angular4-paystack-embed>

**Comment by ashinzekene** [comment]
Try testing with the `angular4-component`, or listening for the `paymentInit` event, like:
```html
<angular4-paystack-embed *ngIf="show" key=
  "pk_test_33c2437bd12c2e1c5358c7701791c02" email="{{email}}" amount="5000000"
  ref="{{ref}}" class="'btn btn-primary'"
  (paymentInit)="listenForInit()"
  (close)="paymentCancel($event)" 
  (callback)="paymentDone($event)">
  <span class="spinner spinner-inline">
    Loading...
  </span>
  <span>Loading.</span>
</angular4-paystack-embed>
```

**Comment by ajanieniolasolomon** [comment]
The paymentInit is work but the callback still not working is there a way
to track the success of the transaction with the paymentInit option

**Comment by ashinzekene** [comment]
No. I'd check and confirm.

**Comment by ajanieniolasolomon** [comment]
Thanks for the help

**Comment by ashinzekene** [comment]
I have checked it and verified it works. Please be sure you're not doing anything wrong

**Comment by ajanieniolasolomon** [comment]
Is it the  callback function

**Comment by ajanieniolasolomon** [comment]
I have found problem it is the if statement

**Comment by ashinzekene** [comment]
Okay
