### ISSUE TITLE
Bug related to Angular @common8

### ISSUE THREAD

**Issue by jowc** [ashinzekene/angular4-paystack#62]
Latest Angular @common13.*, because of this issue. I'm unable to install this library in my local project

**Comment by ashinzekene** [comment]
Can you please explain the issue you're facing

**Comment by jowc** [comment]
Great job.
It seems like an outdated issue with the library angular modules with the current angular 13. I added **`--force`** flag which fixed it.
Secondly, please how can I attach custom metadata. It isn't specified in the docs.
