### ISSUE TITLE
Dependency resolution issue in @angular/common@13.1.3

### ISSUE THREAD

**Issue by adinortey360** [ashinzekene/angular4-paystack#64]
Unable to install the package on Angular 13npm ERR! Found: @angular/common@13.1.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"8.0.3 - 12.*" from angular4-paystack@3.0.2
npm ERR! node_modules/angular4-paystack
npm ERR!   angular4-paystack@"*" from the root project

**Comment by ashinzekene** [comment]
The library has not been updated to support angular 12. You can get around this in the mean time by running

`npm install --legacy-peer-deps`

**Comment by adinortey360** [comment]
Great! I will try this out.
