### ISSUE TITLE
metadata not updating on dashboard

### ISSUE THREAD

**Issue by glimz** [ashinzekene/angular4-paystack#68]
Trying to use metadata to include custom attributes, however, it is not updating on the dashboard. I am using this documentation: https://paystack.com/docs/payments/metadata/

**What I am doing**
```
options: PaystackOptions = {
    amount: 50000,
    email: 'user@mail.com',
    ref: `${Math.ceil(Math.random() * 10e10)}`,

    metadata: {
      phone: "123456781",
      full_name: "testing testing",

         custom_fields: [
          {
            display_name: 'Route',
            variable_name: 'route',
            value: this.from + '-' + this.to,
          },
      ]
    }
  }

```
```
<button
angular4-paystack
[paystackOptions]="options"
[metadata]="options.metadata"
(paymentInit)="paymentInit()"
(onClose)="paymentCancel()"
(callback)="paymentDone($event)"
>
Pay with Paystack
</button>
```
**Current behaviour**
full name and phone number not updated
custom field not updated

**What I am expecting**
I am expecting to see the custom field on the paystack dashboard.
Execting to see the phone number and full name updated on the paystack dashboard

**Comment by glimz** [comment]
Tried to use postman to send a post request (create a transaction), and it is the same issue. I assume the problem is with the paystack API.

**Comment by ashinzekene** [comment]
The documentation says that you'd see the custom field value in your dashboard (i.e the `Route` and the route value like so
<img width="715" alt="image" src="https://user-images.githubusercontent.com/20991583/180645180-397ae8c5-736d-4921-b3dc-6157ec62747b.png">

The phone & full name are returned with the API response
