### ISSUE TITLE
Not compatible with Capacitor 5 and above 

### ISSUE THREAD

**Issue by chronicles-appdev** [ashinzekene/angular4-paystack#79]
Please help update this plugin as it's affecting some of our apps that is using capacitor 5+

**Comment by ashinzekene** [comment]
You should clearly explain the issues you're facing, add environment details and repro steps when creating an issue

**Comment by chronicles-appdev** [comment]
Okay

**Comment by chronicles-appdev** [comment]
When i try ti install 
This is the error i'm getting

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: Learn Africa eReader@2
npm ERR! Found: @angular/common@16.1.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^16.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"8.0.0 - 15" from angular4-paystack@3.1.1
npm ERR! node_modules/angular4-paystack
npm ERR!   angular4-paystack@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR!

**Comment by chronicles-appdev** [comment]
And this is from my package.json 



  "dependencies": {
    "@angular/animations": "^16.0.0",
    "@angular/common": "^16.0.0",
    "@angular/compiler": "^16.0.0",
    "@angular/core": "^16.0.0",
    "@angular/forms": "^16.0.0",
    "@angular/platform-browser": "^16.0.0",
    "@angular/platform-browser-dynamic": "^16.0.0",
    "@angular/router": "^16.0.0",
    "@capacitor/android": "5.0.3",
    "@capacitor/app": "5.0.2",
    "@capacitor/core": "5.0.3",
    "@capacitor/filesystem": "^5.0.2",
    "@capacitor/haptics": "5.0.2",
    "@capacitor/ios": "5.0.3",
    "@capacitor/keyboard": "5.0.2",
    "@capacitor/local-notifications": "^5.0.2",
    "@capacitor/status-bar": "5.0.2",
    "@ionic/angular": "^7.0.0",
    "ionicons": "^7.0.0",
    "ngx-extended-pdf-viewer": "^17.0.0-alpha.6",
    "rxjs": "~7.8.0",
    "swiper": "^9.3.2",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },

**Comment by chronicles-appdev** [comment]
> 
When i try ti install
This is the error i'm getting

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: Learn Africa eReader@2
npm ERR! Found: @angular/common@16.1.1
npm ERR! node_modules/@angular/common
npm ERR! @angular/common@"^16.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"8.0.0 - 15" from angular4-paystack@3.1.1
npm ERR! node_modules/angular4-paystack
npm ERR! angular4-paystack@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!

**Comment by chronicles-appdev** [comment]
> You should clearly explain the issues you're facing, add environment details and repro steps when creating an issue. Helps reduce back and forth

And this is from my package.json

"dependencies": {
"@angular/animations": "^16.0.0",
"@angular/common": "^16.0.0",
"@angular/compiler": "^16.0.0",
"@angular/core": "^16.0.0",
"@angular/forms": "^16.0.0",
"@angular/platform-browser": "^16.0.0",
"@angular/platform-browser-dynamic": "^16.0.0",
"@angular/router": "^16.0.0",
"@capacitor/android": "5.0.3",
"@capacitor/app": "5.0.2",
"@capacitor/core": "5.0.3",
"@capacitor/filesystem": "^5.0.2",
"@capacitor/haptics": "5.0.2",
"@capacitor/ios": "5.0.3",
"@capacitor/keyboard": "5.0.2",
"@capacitor/local-notifications": "^5.0.2",
"@capacitor/status-bar": "5.0.2",
"@ionic/angular": "^7.0.0",
"ionicons": "^7.0.0",
"ngx-extended-pdf-viewer": "^17.0.0-alpha.6",
"rxjs": "~7.8.0",
"swiper": "^9.3.2",
"tslib": "^2.3.0",
"zone.js": "~0.13.0"
},

**Comment by ashinzekene** [comment]
As a temporary fix try installing with this flag `--legacy-peer-deps`

**Comment by harmonizerblinks** [comment]
> As a temporary fix try installing with this flag `--legacy-peer-deps`

this temporary fix does not work when deploying using a pipeline. the error prevent app from deploying.

**Comment by harmonizerblinks** [comment]
can you upgrade the library to support the latest version of angular

**Comment by ashinzekene** [comment]
Published the release, you can re-open this is you still have this issue
