### ISSUE TITLE
split_code param needed

### ISSUE THREAD

**Issue by DevDianDankie** [ashinzekene/angular4-paystack#83]
Hi

I see there is an open pr to get split_code in as an option. I am currently also in need of that option.

<img width="739" alt="image" src="https://github.com/ashinzekene/angular4-paystack/assets/63459153/0f96a2d7-e225-4c90-9b88-7639bb9d6961">

https://paystack.com/docs/payments/accept-payments/

**Comment by ashinzekene** [comment]
Fixed in the latest release
