### ISSUE TITLE
angular4-paystack is compatible with Angular 17

### ISSUE THREAD

**Issue by emmanuelU17** [ashinzekene/angular4-paystack#84]
Current version isn't compatible with an Angular 17 project

<img width="815" alt="image" src="https://github.com/ashinzekene/angular4-paystack/assets/80619808/0bfc259c-f763-437b-b921-40703df21d88">

**Comment by ashinzekene** [comment]
Would update the package this week

**Comment by kegbo** [comment]
Does not work with Angular 16

**Comment by peggylicious** [comment]
Hello @ashinzekene not working with angular17 even i used --force. I had to use --legacy-peer-deps
![angular-paystack](https://github.com/ashinzekene/angular4-paystack/assets/31275819/d1152e5d-902b-4fd6-bc44-d6233a92d23c)

**Comment by ashinzekene** [comment]
Fixing in #86

**Comment by ashinzekene** [comment]
Fixed in the latest release
