### ISSUE TITLE
Cannot add to angular 17 project

### ISSUE THREAD

**Issue by emmanuelU17** [ashinzekene/angular4-paystack#90]
Still the same issue I had previously. I am trying to add this to my angular 17 project. The error comes from angular4-paystack `@angular/common@8.0.0 - ^17.`. I ` --legacy-peer-deps` but this causes an issue in my pipeline.

<img width="813" alt="image" src="https://github.com/ashinzekene/angular4-paystack/assets/80619808/976a3f18-5e09-4aed-aa84-a2da8e55b7a6">

**Comment by ashinzekene** [comment]
Thanks for reporting. This is fixed now
