### ISSUE TITLE
Angular 17 Directive - 

### ISSUE THREAD

**Issue by BeetrootToYourself** [ashinzekene/angular4-paystack#93]
Hi There, 

Firstly thanks for this. Definitely speeds up the process. 
Think there may be bug introduced in the last patches:

Console reads:
ANGULAR-PAYSTACK: Insert a callback output like so (callback)='PaymentComplete($event)' to check payment status

Seems the callback is not passing all the way through - this is true using both the AngularPaystackComponent and the AngularPaystackDirective.

Paystack is being provided in the app module:  Angular4PaystackModule.forRoot()

**Comment by ashinzekene** [comment]
Just tested and it works, can you share what you're doing or [follow the example here](https://github.com/ashinzekene/angular4-paystack/tree/master/src/app)
