### ISSUE TITLE
"subscription_code" is not included in the response payload when a plan is added to the request payload.

### ISSUE THREAD

**Issue by humanityjs** [ashinzekene/angular4-paystack#95]
Hi there,

I'm having this issue where the "subscription_code" is not returned with the payload after a successful payment. I can confirm that the subscription was created on the paystack dashboard but the code is not returned.

Any idea what I might be doing wrong?

**Comment by ashinzekene** [comment]
You should create a server endpoint to verify the transaction and get the subscription. The frontend is only for status verification

https://paystack.com/docs/payments/accept-payments/#handle-the-callback-method
